In [1]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv( 'data/softmax.txt',sep=' ', header=None)
df

   0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [15]:
x_data = df.iloc[:, :2].values.astype(np.float32)
y_data = df.iloc[:, 2:].values

In [16]:
x_data.shape

(8, 2)

In [7]:
y_data.shape

(8, 3)

In [18]:
# z = matmul(x,w) +b 
# hx = softmax( z )
dense = Dense(units=3, input_dim=2, activation='softmax')# w:2x3[특정데이터,라벨], b:3 [라벨의갯수]
dense(x_data)

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[3.7538832e-01, 5.8528793e-01, 3.9323758e-02],
       [2.5354579e-01, 7.3441768e-01, 1.2036599e-02],
       [6.5035015e-02, 9.2309815e-01, 1.1866918e-02],
       [4.3197446e-02, 9.5597684e-01, 8.2570082e-04],
       [6.0283318e-02, 9.3965518e-01, 6.1569393e-05],
       [2.5008792e-02, 9.3628740e-01, 3.8703788e-02],
       [2.3740325e-02, 9.7605407e-01, 2.0564806e-04],
       [1.2922419e-02, 9.8702687e-01, 5.0728813e-05]], dtype=float32)>

In [19]:
w, b = dense.get_weights()
print(w)
print('------')
print(b)

[[ 0.830129   0.6548815 -0.6345422]
 [ 0.2689501  1.0635881  0.9421606]]
------
[0. 0. 0.]

In [23]:
x_data.shape

(8, 2)

In [27]:
z = tf.matmul(x_data, w) +b
hx = tf.nn.softmax(z)
hx.numpy().argmax(axis=1)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
dense = Dense(units=3, input_dim=2, activation='softmax')
model = Sequential([dense])
model.compile( loss='categorical_crossentropy', optimizer=Adam(0.1) , metrics=['acc'])
h = model.fit( x_data, y_data, epochs=500)

Epoch 1/500

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 389ms/step - acc: 0.5000 - loss: 1.6636
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5000 - loss: 1.1299
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.3750 - loss: 1.1492
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.2500 - loss: 1.2688
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.3750 - loss: 1.1284
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.6250 - loss: 0.9877
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 0.9965
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.5000 - loss: 1.0559
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 1.0628
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5000 - loss: 1.0094
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5000 - loss: 0.9341
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.5000 - loss: 0.8921
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.6250 - loss: 0.9058
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.9282
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.6250 - loss: 0.9114
Epoch 16/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.8642
Epoch 17/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.5000 - loss: 0.8275
Epoch 18/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.8222
Epoch 19/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.6250 - loss: 0.8308
Epoch 20/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.8284
Epoch 21/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.8080
Epoch 22/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.7802
Epoch 23/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.6250 - loss: 0.7619
Epoch 24/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.7592
Epoch 25/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - acc: 0.6250 - loss: 0.7601
Epoch 26/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.7512
Epoch 27/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.7341
Epoch 28/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.7198
Epoch 29/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.6250 - loss: 0.7133
Epoch 30/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.6250 - loss: 0.7095
Epoch 31/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.6250 - loss: 0.7035
Epoch 32/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6250 - loss: 0.6949
Epoch 33/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 0.6859
Epoch 34/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.8750 - loss: 0.6784
Epoch 35/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.6250 - loss: 0.6726
Epoch 36/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 0.6669
Epoch 37/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7500 - loss: 0.6612
Epoch 38/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.6250 - loss: 0.6560
Epoch 39/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.5000 - loss: 0.6510
Epoch 40/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.5000 - loss: 0.6449
Epoch 41/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.5000 - loss: 0.6384
Epoch 42/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - acc: 0.7500 - loss: 0.6335
Epoch 43/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7500 - loss: 0.6304
Epoch 44/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.8750 - loss: 0.6269
Epoch 45/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.8750 - loss: 0.6214
Epoch 46/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.6156
Epoch 47/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.6250 - loss: 0.6113
Epoch 48/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.6250 - loss: 0.6085
Epoch 49/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.6250 - loss: 0.6052
Epoch 50/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.6250 - loss: 0.6008
Epoch 51/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - acc: 0.6250 - loss: 0.5963
Epoch 52/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.8750 - loss: 0.5925
Epoch 53/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.8750 - loss: 0.5893
Epoch 54/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.8750 - loss: 0.5859
Epoch 55/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.5824
Epoch 56/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7500 - loss: 0.5790
Epoch 57/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 0.5757
Epoch 58/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7500 - loss: 0.5723
Epoch 59/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.6250 - loss: 0.5689
Epoch 60/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 0.5660
Epoch 61/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7500 - loss: 0.5632
Epoch 62/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.8750 - loss: 0.5601
Epoch 63/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.8750 - loss: 0.5569
Epoch 64/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 0.5538
Epoch 65/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.5511
Epoch 66/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 0.5484
Epoch 67/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7500 - loss: 0.5456
Epoch 68/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.8750 - loss: 0.5427
Epoch 69/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.8750 - loss: 0.5400
Epoch 70/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.8750 - loss: 0.5374
Epoch 71/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.8750 - loss: 0.5347
Epoch 72/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.8750 - loss: 0.5321
Epoch 73/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.8750 - loss: 0.5296
Epoch 74/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.8750 - loss: 0.5271
Epoch 75/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.8750 - loss: 0.5245
Epoch 76/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.8750 - loss: 0.5220
Epoch 77/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.8750 - loss: 0.5196
Epoch 78/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.8750 - loss: 0.5172
Epoch 79/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.8750 - loss: 0.5148
Epoch 80/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.5124
Epoch 81/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.5101
Epoch 82/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 1.0000 - loss: 0.5078
Epoch 83/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.5055
Epoch 84/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 1.0000 - loss: 0.5032
Epoch 85/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.5010
Epoch 86/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4987
Epoch 87/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4965
Epoch 88/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4944
Epoch 89/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4922
Epoch 90/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4901
Epoch 91/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4879
Epoch 92/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4858
Epoch 93/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4838
Epoch 94/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4817
Epoch 95/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4797
Epoch 96/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4777
Epoch 97/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4756
Epoch 98/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4737
Epoch 99/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4717
Epoch 100/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4697
Epoch 101/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4678
Epoch 102/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4659
Epoch 103/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - acc: 1.0000 - loss: 0.4640
Epoch 104/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4621
Epoch 105/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4602
Epoch 106/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4583
Epoch 107/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4565
Epoch 108/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4547
Epoch 109/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4528
Epoch 110/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4510
Epoch 111/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4492
Epoch 112/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4475
Epoch 113/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 1.0000 - loss: 0.4457
Epoch 114/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - acc: 1.0000 - loss: 0.4440
Epoch 115/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4422
Epoch 116/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4405
Epoch 117/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4388
Epoch 118/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4371
Epoch 119/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.4354
Epoch 120/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4338
Epoch 121/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - acc: 1.0000 - loss: 0.4321
Epoch 122/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4305
Epoch 123/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4288
Epoch 124/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4272
Epoch 125/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4256
Epoch 126/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.4240
Epoch 127/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4224
Epoch 128/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4208
Epoch 129/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4193
Epoch 130/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4177
Epoch 131/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4162
Epoch 132/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4147
Epoch 133/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4131
Epoch 134/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4116
Epoch 135/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4101
Epoch 136/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.4086
Epoch 137/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.4072
Epoch 138/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4057
Epoch 139/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.4042
Epoch 140/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - acc: 1.0000 - loss: 0.4028
Epoch 141/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.4014
Epoch 142/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3999
Epoch 143/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3985
Epoch 144/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3971
Epoch 145/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3957
Epoch 146/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3943
Epoch 147/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3930
Epoch 148/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3916
Epoch 149/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 1.0000 - loss: 0.3902
Epoch 150/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3889
Epoch 151/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3875
Epoch 152/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3862
Epoch 153/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 1.0000 - loss: 0.3849
Epoch 154/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3836
Epoch 155/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3823
Epoch 156/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3810
Epoch 157/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3797
Epoch 158/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3784
Epoch 159/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - acc: 1.0000 - loss: 0.3771
Epoch 160/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3759
Epoch 161/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 1.0000 - loss: 0.3746
Epoch 162/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3734
Epoch 163/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - acc: 1.0000 - loss: 0.3721
Epoch 164/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3709
Epoch 165/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3697
Epoch 166/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3685
Epoch 167/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3672
Epoch 168/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.3660
Epoch 169/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 1.0000 - loss: 0.3649
Epoch 170/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3637
Epoch 171/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3625
Epoch 172/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3613
Epoch 173/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3602
Epoch 174/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3590
Epoch 175/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3579
Epoch 176/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3567
Epoch 177/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3556
Epoch 178/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 1.0000 - loss: 0.3545
Epoch 179/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3533
Epoch 180/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3522
Epoch 181/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3511
Epoch 182/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3500
Epoch 183/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3489
Epoch 184/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3478
Epoch 185/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3468
Epoch 186/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3457
Epoch 187/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3446
Epoch 188/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3435
Epoch 189/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3425
Epoch 190/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3414
Epoch 191/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3404
Epoch 192/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.3394
Epoch 193/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3383
Epoch 194/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3373
Epoch 195/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3363
Epoch 196/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3353
Epoch 197/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3343
Epoch 198/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 1.0000 - loss: 0.3333
Epoch 199/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3323
Epoch 200/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3313
Epoch 201/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3303
Epoch 202/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3293
Epoch 203/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - acc: 1.0000 - loss: 0.3284
Epoch 204/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3274
Epoch 205/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.3264
Epoch 206/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3255
Epoch 207/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3245
Epoch 208/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3236
Epoch 209/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3226
Epoch 210/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 1.0000 - loss: 0.3217
Epoch 211/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3208
Epoch 212/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3198
Epoch 213/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3189
Epoch 214/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 1.0000 - loss: 0.3180
Epoch 215/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3171
Epoch 216/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3162
Epoch 217/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - acc: 1.0000 - loss: 0.3153
Epoch 218/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3144
Epoch 219/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3135
Epoch 220/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3126
Epoch 221/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3117
Epoch 222/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3109
Epoch 223/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.3100
Epoch 224/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3091
Epoch 225/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 1.0000 - loss: 0.3083
Epoch 226/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3074
Epoch 227/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3065
Epoch 228/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3057
Epoch 229/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3048
Epoch 230/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.3040
Epoch 231/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3032
Epoch 232/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.3023
Epoch 233/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3015
Epoch 234/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - acc: 1.0000 - loss: 0.3007
Epoch 235/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.2999
Epoch 236/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - acc: 1.0000 - loss: 0.2990
Epoch 237/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.2982
Epoch 238/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.2974
Epoch 239/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.2966
Epoch 240/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 1.0000 - loss: 0.2958
Epoch 241/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.2950
Epoch 242/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.2942
Epoch 243/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.2934
Epoch 244/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 1.0000 - loss: 0.2927
Epoch 245/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.2919
Epoch 246/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.2911
Epoch 247/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.2903
Epoch 248/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.2896
Epoch 249/500

In [29]:
w, b = dense.get_weights()
print(w)
print('------')
print(b)

[[ 0.11884087  0.0190857  -0.22440644]
 [ 1.5181458  -1.2581215  -4.2925115 ]]
------
[-13.059654    3.2337244  17.058071 ]

In [32]:
dense( x_data).numpy().argmax(axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0])

In [34]:
y_data.argmax(axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0])

In [36]:
model.predict( x_data ).argmax(axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

array([2, 2, 2, 1, 1, 1, 0, 0])

In [ ]:
## iris 데이터셋 케라스로 학습하고
## 1,2행의 예측값을 구하시요.

In [38]:
from sklearn.datasets import load_iris
from keras.utils import to_categorical

In [39]:
iris = load_iris( as_frame=True)
iris['frame']

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [40]:
x_data = iris['data'].values
y_data = to_categorical( iris['target'] )

In [41]:
dense = Dense(units=3, input_dim=4, activation='softmax')
model = Sequential([dense])
model.compile( loss='categorical_crossentropy', optimizer=Adam(0.1) , metrics=['acc'])
h = model.fit( x_data, y_data, epochs=500)

Epoch 1/500

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.3200 - loss: 1.8717
Epoch 2/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.6600 - loss: 1.0303
Epoch 3/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.6267 - loss: 0.7091
Epoch 4/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7333 - loss: 0.4988
Epoch 5/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7867 - loss: 0.4655
Epoch 6/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7400 - loss: 0.4212
Epoch 7/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8933 - loss: 0.3695
Epoch 8/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7667 - loss: 0.3974
Epoch 9/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8667 - loss: 0.3546
Epoch 10/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9000 - loss: 0.3249
Epoch 11/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8800 - loss: 0.3100
Epoch 12/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9400 - loss: 0.2743
Epoch 13/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.2635
Epoch 14/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - loss: 0.2597
Epoch 15/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9533 - loss: 0.2438
Epoch 16/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9467 - loss: 0.2398
Epoch 17/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9400 - loss: 0.2368
Epoch 18/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9200 - loss: 0.2321
Epoch 19/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9533 - loss: 0.2321
Epoch 20/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1941
Epoch 21/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9467 - loss: 0.2125
Epoch 22/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1972
Epoch 23/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1881
Epoch 24/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1848
Epoch 25/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1786
Epoch 26/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1699
Epoch 27/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1711
Epoch 28/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1654
Epoch 29/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1623
Epoch 30/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1587
Epoch 31/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9533 - loss: 0.1588
Epoch 32/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1562
Epoch 33/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9667 - loss: 0.1488
Epoch 34/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1450
Epoch 35/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1442
Epoch 36/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1404
Epoch 37/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1380
Epoch 38/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1368
Epoch 39/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1365
Epoch 40/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1353
Epoch 41/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1336
Epoch 42/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.1295
Epoch 43/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1250
Epoch 44/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1303
Epoch 45/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1322
Epoch 46/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9467 - loss: 0.1367
Epoch 47/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1369
Epoch 48/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1336
Epoch 49/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1243
Epoch 50/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9467 - loss: 0.1371
Epoch 51/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9400 - loss: 0.1704
Epoch 52/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9533 - loss: 0.1240
Epoch 53/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1289
Epoch 54/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1283
Epoch 55/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9533 - loss: 0.1151
Epoch 56/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1054
Epoch 57/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.1083
Epoch 58/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.1120
Epoch 59/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1028
Epoch 60/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.1045
Epoch 61/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1051
Epoch 62/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.1069
Epoch 63/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1019
Epoch 64/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0952
Epoch 65/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.1022
Epoch 66/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1020
Epoch 67/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.1012
Epoch 68/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9533 - loss: 0.1277
Epoch 69/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9467 - loss: 0.1130
Epoch 70/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1058
Epoch 71/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0974
Epoch 72/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.1180
Epoch 73/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1227
Epoch 74/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9867 - loss: 0.0928
Epoch 75/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0924
Epoch 76/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9667 - loss: 0.1058
Epoch 77/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0990
Epoch 78/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0892
Epoch 79/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0886
Epoch 80/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0918
Epoch 81/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0883
Epoch 82/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0860
Epoch 83/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9667 - loss: 0.0873
Epoch 84/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0905
Epoch 85/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0944
Epoch 86/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9667 - loss: 0.0846
Epoch 87/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0850
Epoch 88/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0832
Epoch 89/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0835
Epoch 90/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0816
Epoch 91/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0806
Epoch 92/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.0825
Epoch 93/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0843
Epoch 94/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.0962
Epoch 95/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9733 - loss: 0.0890
Epoch 96/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0795
Epoch 97/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0846
Epoch 98/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0770
Epoch 99/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0819
Epoch 100/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0781
Epoch 101/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0799
Epoch 102/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0757
Epoch 103/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0782
Epoch 104/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0755
Epoch 105/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0776
Epoch 106/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9667 - loss: 0.0763
Epoch 107/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0761
Epoch 108/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0770
Epoch 109/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0725
Epoch 110/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0764
Epoch 111/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0757
Epoch 112/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0729
Epoch 113/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0749
Epoch 114/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0754
Epoch 115/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0745
Epoch 116/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0718
Epoch 117/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0738
Epoch 118/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0730
Epoch 119/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0715
Epoch 120/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0739
Epoch 121/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0741
Epoch 122/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0708
Epoch 123/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9800 - loss: 0.0741
Epoch 124/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.0807
Epoch 125/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0694
Epoch 126/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0764
Epoch 127/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0742
Epoch 128/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0703
Epoch 129/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0746
Epoch 130/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0708
Epoch 131/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9800 - loss: 0.0725
Epoch 132/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0685
Epoch 133/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0760
Epoch 134/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.0815
Epoch 135/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0703
Epoch 136/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0732
Epoch 137/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.0833
Epoch 138/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0887
Epoch 139/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0691
Epoch 140/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0691
Epoch 141/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0699
Epoch 142/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0681
Epoch 143/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0661
Epoch 144/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0685
Epoch 145/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0735
Epoch 146/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0734
Epoch 147/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.0823
Epoch 148/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0814
Epoch 149/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0717
Epoch 150/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0661
Epoch 151/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0703
Epoch 152/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0707
Epoch 153/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9867 - loss: 0.0696
Epoch 154/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0697
Epoch 155/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0651
Epoch 156/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0693
Epoch 157/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.0849
Epoch 158/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0636
Epoch 159/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.0689
Epoch 160/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9733 - loss: 0.0675
Epoch 161/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0663
Epoch 162/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0686
Epoch 163/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0705
Epoch 164/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0716
Epoch 165/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9933 - loss: 0.0557
Epoch 166/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9733 - loss: 0.0747
Epoch 167/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9667 - loss: 0.0731
Epoch 168/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0610
Epoch 169/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0641
Epoch 170/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0659
Epoch 171/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0666
Epoch 172/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0620
Epoch 173/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0690
Epoch 174/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0689
Epoch 175/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9733 - loss: 0.0638
Epoch 176/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0636
Epoch 177/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0631
Epoch 178/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0598
Epoch 179/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0627
Epoch 180/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0619
Epoch 181/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0640
Epoch 182/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0641
Epoch 183/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9867 - loss: 0.0613
Epoch 184/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0612
Epoch 185/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0616
Epoch 186/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0673
Epoch 187/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0675
Epoch 188/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.0768
Epoch 189/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0576
Epoch 190/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0660
Epoch 191/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0727
Epoch 192/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0759
Epoch 193/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0684
Epoch 194/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9667 - loss: 0.0902
Epoch 195/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9800 - loss: 0.0656
Epoch 196/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0701
Epoch 197/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0629
Epoch 198/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0630
Epoch 199/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0589
Epoch 200/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0599
Epoch 201/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0599
Epoch 202/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0601
Epoch 203/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0572
Epoch 204/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0681
Epoch 205/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9667 - loss: 0.0795
Epoch 206/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0680
Epoch 207/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9867 - loss: 0.0642
Epoch 208/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0734
Epoch 209/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0671
Epoch 210/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0583
Epoch 211/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0603
Epoch 212/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0625
Epoch 213/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0593
Epoch 214/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0593
Epoch 215/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0568
Epoch 216/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.0575
Epoch 217/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0568
Epoch 218/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0639
Epoch 219/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0635
Epoch 220/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0571
Epoch 221/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0645
Epoch 222/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0580
Epoch 223/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0654
Epoch 224/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0781
Epoch 225/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0632
Epoch 226/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9800 - loss: 0.0621
Epoch 227/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0677
Epoch 228/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.0718
Epoch 229/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9867 - loss: 0.0541
Epoch 230/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0686
Epoch 231/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0733
Epoch 232/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0589
Epoch 233/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0674
Epoch 234/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0609
Epoch 235/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0588
Epoch 236/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9867 - loss: 0.0545
Epoch 237/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9800 - loss: 0.0562
Epoch 238/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0641
Epoch 239/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0693
Epoch 240/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0630
Epoch 241/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0560
Epoch 242/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9867 - loss: 0.0595
Epoch 243/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.0599
Epoch 244/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9867 - loss: 0.0575
Epoch 245/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.0651
Epoch 246/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9867 - loss: 0.0550
Epoch 247/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0558
Epoch 248/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9800 - loss: 0.0551
Epoch 249/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9733 - loss: 0.0609
Epoch 250/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0558
Epoch 251/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9867 - loss: 0.0594
Epoch 252/500

In [45]:
model.predict( x_data[[0,1]] ).argmax(axis=1) # 2x4 4x3

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

array([0, 0])